const Data = [
  {
    id: 1,
    firstName: "Abdul Azeez",
    lastName: "Abdul Afeez",
    stateOfOrigin: "Kwara State",
    sex: "Male",
    email: "olamilekan@gmail.com",
    phoneNumber: "09137139186",
    courseStudy: "Computer Science",
    yearsOfStudy: "4 Years",
  },
  {
    id: 2,
    firstName: "Adejare",
    lastName: "Sulaimon",
    stateOfOrigin: "Ogun State",
    sex: "Male",
    email: "babatunde@gmail.com",
    phoneNumber: "09037339188",
    courseStudy: "Business Admin",
    yearsOfStudy: "4 Years",
  },
  {
    id: 3,
    firstName: "Abdul Azeez",
    lastName: "Aliyah",
    stateOfOrigin: "Kwara State",
    sex: "Female",
    email: "abiodun@gmail.com",
    phoneNumber: "09133129181",
    courseStudy: "Medicine",
    yearsOfStudy: "5 Years",
  },
  {
    id: 4,
    firstName: "Abdul Azeez",
    lastName: "Abdul Alim",
    stateOfOrigin: "Kwara State",
    sex: "Male",
    email: "tomiwa@gmail.com",
    phoneNumber: "09131139196",
    courseStudy: "Law",
    yearsOfStudy: "5 Years",
  },
  {
    id: 5,
    firstName: "Abdul Azeez",
    lastName: "Abdulahi",
    stateOfOrigin: "Kwara State",
    sex: "Male",
    email: "olawale@gmail.com",
    phoneNumber: "09137739186",
    courseStudy: "Education",
    yearsOfStudy: "4 Years",
  },
];

export default Data